package br.com.kanleitos.models.enums;

public enum TipoStatusLeito {
	DESOCUPADO, OCUPADO_COMUM, OCUPADO_ISOLAMENTO_RESPIRATORIO, OCUPADO_PRECAUCAO_CONTATO, BLOQUEADO_REFORMA, BLOQUEADO_RH, AGUARDANDO_LIMPEZA, OCUPADO_REVERSO_PROTETOR, INATIVO;

}
